---
- name: Install maven
  apt: pkg=maven state=present

- name: Download OpenTripPlanner
  git: repo={{ otp_repo }}
       dest={{ otp_bin_dir }}
       version={{ otp_version }}

- name: Set OpenTripPlanner Session Timeout
  lineinfile: dest={{ otp_bin_dir }}/src/client/WEB-INF/web.xml regexp="(^|\W)<session-timeout>30</session-timeout>$" line="\t\t<session-timeout>{{ otp_session_timeout }}</session-timeout>"
  when: otp_session_timeout is defined

- name: Compile OpenTripPlanner
  command: mvn clean package -DskipTests
           chdir={{ otp_bin_dir }}
           creates={{ otp_bin_dir }}/otp-core/target/otp.jar

- name: Create service account for OpenTripPlanner
  user: name={{ otp_user }}
        system=yes
        home=/var/lib/{{ otp_user }}
        shell=/bin/false
        state=present

- name: Create data directory
  file: path={{ otp_data_dir }} mode=0775 state=directory

- name: Install upstart service
  template: src=otp.conf.j2 dest=/etc/init/otp.conf
  notify: Restart OpenTripPlanner
