---
- name: Check if OpenTripPlanner service exists
  stat: path=/etc/init/otp.conf
  register: otp_service

- name: Stop OpenTripPlanner
  service: name=otp state=stopped
  when: otp_service.stat.exists

- name: Create OpenTripPlanner binary directory
  file: path={{ otp_bin_dir }} mode=0775 state=directory

- name: Download OpenTripPlanner
  get_url: url=http://maven.conveyal.com.s3.amazonaws.com/org/opentripplanner/otp/{{ otp_version }}/otp-{{ otp_version }}.jar
           dest={{ otp_bin_dir }}
           mode=0775

- name: Create service account for OpenTripPlanner
  user: name={{ otp_user }}
        system=yes
        home=/var/lib/{{ otp_user }}
        shell=/bin/false
        state=present

- name: Create data directory
  file: path={{ otp_data_dir }} mode=0775 state=directory

- name: Install upstart service
  template: src=otp.conf.j2 dest=/etc/init/otp.conf
  notify: Restart OpenTripPlanner
