---
- hosts: all

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes

  vars:
    java_major_version: "8"
    java_version: "8u161*"

  roles:
    - { role: "azavea.opentripplanner" }
